### ISSUE TITLE
App running with errors, giving 404

### ISSUE THREAD

**Issue by MariusStuparu** [nodee-apps/cms#1]
Hello,

I checked out the repo, ran `npm install` (modules installed without errors), started local mongod, and tried to start both versions, `node debug.js` and `node release.js` but i get the errors listed below, and going to `localhost:8088` or `localhost:8088/admin` gives a 404 error. I changed the port in config-debug because it was conflicting with other apps.

Node is v0.12.0, NPM v2.5.1, MongoDB v3.0.5, Windows 7 x64.

I am behind a corporate firewall/proxy, so this could be the problem (even though it is configured at system level). Where can I add the proxy url and credentials?

```
======= 2015-08-24 13:29:31: framework.install('package', 'https://cdn.rawgit.com/nodejs-enterprise/packages/master/enterprise-total.package') ---> Error: 408: Request Time-out Error: 408: Request Time-out
    at ClientRequest.<anonymous> ([path edited]\node_modules\total.js\utils.js:725:15)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:104:17)
    at TLSSocket.emitTimeout (_http_client.js:536:10)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket.Socket._onTimeout (net.js:340:8)
    at _makeTimerTimeout (timers.js:467:11)
    at Timer.unrefTimeout (timers.js:531:5)
======= 2015-08-24 13:29:31: framework.install('package', 'https://cdn.rawgit.com/nodejs-enterprise/packages/master/enterprise-admin.package') ---> Error: 408: Request Time-out Error: 408: Request Time-out
    at ClientRequest.<anonymous> ([path edited]\cms\node_modules\total.js\utils.js:725:15)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:104:17)
    at TLSSocket.emitTimeout (_http_client.js:536:10)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket.Socket._onTimeout (net.js:340:8)
    at _makeTimerTimeout (timers.js:467:11)
    at Timer.unrefTimeout (timers.js:531:5)
======= 2015-08-24 13:29:31: framework.install('package', 'https://cdn.rawgit.com/nodejs-enterprise/packages/master/enterprise-cms.package') ---> Error: 408: Request Time-out Error: 408: Request Time-out
    at ClientRequest.<anonymous> ([path edited]\node_modules\total.js\utils.js:725:15)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:104:17)
    at TLSSocket.emitTimeout (_http_client.js:536:10)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket.Socket._onTimeout (net.js:340:8)
    at _makeTimerTimeout (timers.js:467:11)
    at Timer.unrefTimeout (timers.js:531:5)
======= 2015-08-24 13:29:42: framework.install('package', 'https://cdn.rawgit.com/nodejs-enterprise/packages/master/enterprise-admin.package') ---> Error: connect ETIMEDOUT Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
======= 2015-08-24 13:29:42: framework.install('package', 'https://cdn.rawgit.com/nodejs-enterprise/packages/master/enterprise-cms.package') ---> Error: connect ETIMEDOUT Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
======= 2015-08-24 13:29:42: framework.install('package', 'https://cdn.rawgit.com/nodejs-enterprise/packages/master/enterprise-total.package') ---> Error: connect ETIMEDOUT Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```

**Comment by matusszabo** [comment]
Hi @MariusStuparu,
thank you for first cms issue :) Yes, problem is with internet connection, seems like app is unable to download total.js packages, and thats why is unable to respond at /admin (admin controllers missing). I'm not sure how to correctly setup your internet/proxy connection (maybe node is ignoring proxy setup), but you can do:
1. manually download all 3 packages in "dependencies" file (enterprise-total.package, enterprise-admin.package, enterprise-cms.package)
2. place into yourapp/packages folder (total.js will load it from local folder instead of internet)
3. remove, rename, or comment "dependencies" file to avoid package duplicities
4. run node debug.js or release.js - there should be no error messages now, if so let me know

thank you

**Comment by MariusStuparu** [comment]
Hey Matusz,

The app started after doing so, and I was able to log in, but there are still resources inside the admin that require remote download. So I think a proxy setting is required for working inside coporate networks.

**Comment by matusszabo** [comment]
@MariusStuparu, what kind of resources ?
If you mean static front-end libraries like angular, your browser is loading it from cdn. You may have no internet connection, or some restrictions (try if you can access it directly) - what errors are in your browser console ?
If you mean resources downloaded by node app from internet, there should be some error message - paste it here, please.

**Comment by MariusStuparu** [comment]
There was an access denied to the Font Awesome CDN stylesheet, that is blocked by out McAfee Web Gateway (I don't know why). The bootstrap css is not blocked, although on the same cdn...

I was able to get around by accepting some security warning, but you should consider including them locally.

**Comment by matusszabo** [comment]
Hi @MariusStuparu,
all resources are now local, if you are running debug mode. Release mode will force all 3rd-party resources to load from cdn. Packages are now part of this project.
