### ISSUE TITLE
Cannot render template - no such file or directory

### ISSUE THREAD

**Issue by poacher2k** [nodee-apps/cms#13]
Hi!

First and foremost, thank you for the work you're doing on this! This node.js CMS is the best I've found so far.

After having followed the installation instructions and then visiting `/admin`, I am given the following error:

```
Cannot render template: View "tmp/enterprise-admin/views/index.html" compilation failed <-- View engine compileSync: reading template file failed <-- ENOENT: no such file or directory, open '/home/poacher2k/development/projectfolder/cms/tmp/enterprise-admin/views/index.html'

Error: View "tmp/enterprise-admin/views/index.html" compilation failed <-- View engine compileSync: reading template file failed <-- ENOENT: no such file or directory, open '/home/poacher2k/development/projectfolder/cms/tmp/enterprise-admin/views/index.html'
    at isValidView (/home/poacher2k/development/projectfolder/cms/node_modules/enterprise-view/lib/view.js:262:45)
    at getCompiledSync (/home/poacher2k/development/projectfolder/cms/node_modules/enterprise-view/lib/view.js:381:9)
    at Object.renderViewSync [as renderSync] (/home/poacher2k/development/projectfolder/cms/node_modules/enterprise-view/lib/view.js:352:23)
    at Object.view (eval at <anonymous> (/home/poacher2k/development/projectfolder/cms/node_modules/total.js/index.js:3015:82), <anonymous>:169:37)
    at Object.Controller.view (eval at <anonymous> (/home/poacher2k/development/projectfolder/cms/node_modules/total.js/index.js:3015:82), <anonymous>:127:25)
    at Object.index (/home/poacher2k/development/projectfolder/cms/tmp/enterprise-admin.package/index.js:525:10)
    at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.doExecute (/home/poacher2k/development/projectfolder/cms/node_modules/total.js/index.js:9761:23)
    at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.execute (/home/poacher2k/development/projectfolder/cms/node_modules/total.js/index.js:9684:15)
    at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.prepare (/home/poacher2k/development/projectfolder/cms/node_modules/total.js/index.js:9727:8)
    at Subscribe.Framework.$load.arr.forEach.arr.forEach.arr.forEach.Framework.log.Framework.logger.Framework.responseStatic.Framework.responseStream.Framework.responseBinary.Framework.responseContent.Framework.mode.Framework._request_continue.self._cors.self._cors.self._cors.Framework.test.Framework._configure.FrameworkPath.exists.Subscribe.urlencoded.Subscribe.doEnd (/home/poacher2k/development/projectfolder/cms/node_modules/total.js/index.js:9850:8)

template: /home/poacher2k/development/projectfolder/cms/tmp/enterprise-admin/views/index.html
errno: -2
code: ENOENT
syscall: open
path: /home/poacher2k/development/projectfolder/cms/tmp/enterprise-admin/views/index.html
errlevel: 3
```

Any idea of what might be causing this?

Cheers!

**Comment by matusszabo** [comment]
Hi @poacher2k , seems like same it is as #10 . Please try it and let us know. thank you.

**Comment by poacher2k** [comment]
Thank you! Will do :)

**Comment by azerck** [comment]
I have received the same error

> Cannot render template: View "tmp/enterprise-admin/views/index.html" compilation failed <-- View engine compileSync: reading template file failed <-- ENOENT: no such file or directory, open '/home/azerck/Desktop/GIT/cms/tmp/enterprise-admin/views/index.html'
> 
> Error: View "tmp/enterprise-admin/views/index.html" compilation failed <-- View engine compileSync: reading template file failed <-- ENOENT: no such file or directory, open '/home/azerck/Desktop/GIT/cms/tmp/enterprise-admin/views/index.html'
>     at isValidView (/home/azerck/Desktop/GIT/cms/node_modules/enterprise-view/lib/view.js:262:45)
>     at getCompiledSync (/home/azerck/Desktop/GIT/cms/node_modules/enterprise-view/lib/view.js:385:9)
>     at Object.renderViewSync [as renderSync](/home/azerck/Desktop/GIT/cms/node_modules/enterprise-view/lib/view.js:352:23)
>     at Object.view (eval at <anonymous> (/home/azerck/Desktop/GIT/cms/node_modules/total.js/index.js:3015:82), <anonymous>:169:37)
>     at Object.Controller.view (eval at <anonymous> (/home/azerck/Desktop/GIT/cms/node_modules/total.js/index.js:3015:82), <anonymous>:127:25)
>     at Object.index (/home/azerck/Desktop/GIT/cms/tmp/enterprise-admin.package/index.js:525:10)
>     at Subscribe.doExecute (/home/azerck/Desktop/GIT/cms/node_modules/total.js/index.js:9761:23)
>     at Subscribe.execute (/home/azerck/Desktop/GIT/cms/node_modules/total.js/index.js:9684:15)
>     at Subscribe.prepare (/home/azerck/Desktop/GIT/cms/node_modules/total.js/index.js:9727:8)
>     at Subscribe.doEnd (/home/azerck/Desktop/GIT/cms/node_modules/total.js/index.js:9850:8)
> 
> template: /home/azerck/Desktop/GIT/cms/tmp/enterprise-admin/views/index.html
> errno: -2
> code: ENOENT
> syscall: open
> path: /home/azerck/Desktop/GIT/cms/tmp/enterprise-admin/views/index.html
> errlevel: 3

**Comment by tomasholovsky** [comment]
Hi @azerck, did you follow instructions in #10?

**Comment by matusszabo** [comment]
Repo was updated, it should be fixed now.
